version: '3.8'

services:
  pacelab-vdot:
    build: .
    container_name: running_pro_app
    restart: always
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - /home/jotape/runningPro/data:/app/data
